### ISSUE TITLE
Tutorial needed

### ISSUE THREAD

**Issue by OliverRayn** [OliverRayn/my_first_project#1]
Hi everyone! I would like to create my own class on C#, but I cannot find how to do it in a proper way. Can you provide some guide how to do it properly. :pray: :pray: :pray:

**Comment by valyatar** [comment]
Create a new console application

1. Start Visual Studio .NET or Visual Studio 2005, and create a new C# console application project named ClassesAndObjects.
2. Save the project.

Create a new class
1. From the Project menu, click Add Class.
In the Add New Item dialog box, for Class name type BaseballTeam, and then click Open.

2. Note In Visual C# 2005, Open is changed to Add.
3. Examine the code for the new class in the Code View window.

**Comment by valyatar** [comment]
Define fields and constructors

1. From the View menu, click Class View. In the Class View window, expand the ClassesAndObjects project, and then expand the ClassesAndObjects namespace. Right-click the BaseballTeam class, choose Add, and then click Add Field.

Note Visual C# 2005 has some design changes. For more information, visit the following Microsoft Web site:
http://msdn2.microsoft.com/en-us/library/t27ahy37.aspx
2. In the C# Field Wizard, set the Field access to private and set the Field type to string. For Field name, type name. Click Finish. This adds the following field to the class:
private string name;
3. Repeat steps 1 and 2 (or type the code manually), to add another field as follows:
private string stadium;
4. Add two more fields, and provide initial field values as follows:
private int wins = 0;
private int defeats = 0;
5. Modify the constructor for the class to initialize the name of the team and the stadium:
public BaseballTeam(string n, string s)
{
   this.name = n;
   this.stadium = s;

}

**Comment by valyatar** [comment]
And finally, you have to create an object like:

BaseballTeam sf = new BaseballTeam("San Francisco Giants", 
                                   "Candlestick Park");

and verify that it works.

Hope I've helped you. Good luck with your project.

**Comment by OliverRayn** [comment]
Thank you so much. I'll try to apply this in my project! :bowing_man: :bowing_man: :bowing_man:
